name: Build RPi Image

on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Build Image
        run: |
          ./build.sh
      
      - uses: actions/upload-artifact@v4
        with:
          name: image
          path: ./deploy/*
