name: Build RPi Image

on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install dependencies
        run: |
          xargs sudo apt-get -y install \
            quilt \
            qemu-user-static \
            debootstrap \
            libarchive-tools \
            arch-test

      - name: Build Image
        run: |
          sudo ./build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: image
          path: ./deploy/*
      
      - uses: ncipollo/release-action@v1
        if: startsWith( github.ref, 'refs/tags' )
        with:
          artifacts: "./deploy/*"
