name: Build RPi Image

on: [push]
jobs:
  build:
    runs-on: [self-hosted, arm64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Image
        run: |
          sudo python build_ci.py